/** Real publisher catalog, verified 2026-10-01. Sources are linked on every item. */
export const STUDY_MOODS = [
  "Deep Focus",
  "Lo-fi",
  "Classical",
  "Ambient",
  "Rain Sounds",
  "Instrumental",
  "Brain Boost",
] as const;
export type StudyMood = (typeof STUDY_MOODS)[number];
export interface CuratedTrack {
  id: string;
  title: string;
  category: StudyMood;
  moods: readonly StudyMood[];
  creator: string;
  artwork: string;
  source: "radio" | "youtube";
  sourceUrl: string;
  watchUrl: string;
  description?: string;
  audioUrl?: string;
  videoId?: string;
  embedUrl?: string;
  durationSeconds?: number;
}
export const CURATED_TRACKS: readonly CuratedTrack[] = [
  {
    id: "somafm-groovesalad",
    title: "Groove Salad",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "A nicely chilled plate of ambient/downtempo beats and grooves.",
    audioUrl: "https://ice6.somafm.com/groovesalad-256-mp3",
    artwork: "https://api.somafm.com/logos/512/groovesalad512.png?v=1780812671",
    watchUrl: "https://somafm.com/groovesalad/",
    sourceUrl: "https://somafm.com/groovesalad/",
    source: "radio",
  },
  {
    id: "somafm-gsclassic",
    title: "Groove Salad Classic",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "The classic (early 2000s) version of a nicely chilled plate of ambient/downtempo beats and grooves.",
    audioUrl: "https://ice6.somafm.com/gsclassic-128-mp3",
    artwork: "https://api.somafm.com/logos/512/gsclassic512.jpg?v=1747344773",
    watchUrl: "https://somafm.com/gsclassic/",
    sourceUrl: "https://somafm.com/gsclassic/",
    source: "radio",
  },
  {
    id: "somafm-groovesalad2",
    title: "Groove Salad 2",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "A different mix of  nicely chilled ambient/downtempo beats and grooves.",
    audioUrl: "https://ice6.somafm.com/groovesalad2-256-mp3",
    artwork:
      "https://api.somafm.com/logos/512/groovesalad2512.png?v=1779933336",
    watchUrl: "https://somafm.com/groovesalad2/",
    sourceUrl: "https://somafm.com/groovesalad2/",
    source: "radio",
  },
  {
    id: "somafm-deepspaceone",
    title: "Deep Space One",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "Deep ambient electronic, experimental and space music. For inner and outer space exploration.",
    audioUrl: "https://ice6.somafm.com/deepspaceone-128-mp3",
    artwork:
      "https://api.somafm.com/logos/512/deepspaceone512.png?v=1378071297",
    watchUrl: "https://somafm.com/deepspaceone/",
    sourceUrl: "https://somafm.com/deepspaceone/",
    source: "radio",
  },
  {
    id: "somafm-dronezone",
    title: "Drone Zone",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "Served best chilled, safe with most medications. Atmospheric textures with minimal beats.",
    audioUrl: "https://ice6.somafm.com/dronezone-256-mp3",
    artwork: "https://api.somafm.com/logos/512/dronezone512.png?v=1299186962",
    watchUrl: "https://somafm.com/dronezone/",
    sourceUrl: "https://somafm.com/dronezone/",
    source: "radio",
  },
  {
    id: "somafm-dz2",
    title: "Drone Zone 2",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "A more eclectic alternative mix of atmospheric textures with minimal beats.",
    audioUrl: "https://ice6.somafm.com/dz2-128-mp3",
    artwork: "https://api.somafm.com/logos/512/dz2512.png?v=1776988037",
    watchUrl: "https://somafm.com/dz2/",
    sourceUrl: "https://somafm.com/dz2/",
    source: "radio",
  },
  {
    id: "somafm-spacestation",
    title: "Space Station Soma",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica.",
    audioUrl: "https://ice6.somafm.com/spacestation-320-mp3",
    artwork:
      "https://api.somafm.com/logos/512/spacestation512.png?v=1299205660",
    watchUrl: "https://somafm.com/spacestation/",
    sourceUrl: "https://somafm.com/spacestation/",
    source: "radio",
  },
  {
    id: "somafm-synphaera",
    title: "Synphaera Radio",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "Featuring the music from an independent record label focused on modern electronic ambient and space music.",
    audioUrl: "https://ice6.somafm.com/synphaera-256-mp3",
    artwork: "https://api.somafm.com/logos/512/synphaera512.jpg?v=1611903618",
    watchUrl: "https://somafm.com/synphaera/",
    sourceUrl: "https://somafm.com/synphaera/",
    source: "radio",
  },
  {
    id: "somafm-n5md",
    title: "n5MD Radio",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "Emotional Experiments in Music: Ambient, modern composition, post-rock, & experimental electronic music",
    audioUrl: "https://ice6.somafm.com/n5md-128-mp3",
    artwork: "https://api.somafm.com/logos/512/n5md512.png?v=1605058529",
    watchUrl: "https://somafm.com/n5md/",
    sourceUrl: "https://somafm.com/n5md/",
    source: "radio",
  },
  {
    id: "somafm-darkzone",
    title: "The Dark Zone",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Ambient"],
    description:
      "The darker side of deep ambient. Music for staring into the Abyss. ",
    audioUrl: "https://ice6.somafm.com/darkzone-256-mp3",
    artwork: "https://api.somafm.com/logos/512/darkzone512.jpg?v=1674958826",
    watchUrl: "https://somafm.com/darkzone/",
    sourceUrl: "https://somafm.com/darkzone/",
    source: "radio",
  },
  {
    id: "somafm-fluid",
    title: "Fluid",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Brain Boost"],
    description:
      "Drown in the electronic sound of instrumental hiphop, future soul and liquid trap.",
    audioUrl: "https://ice6.somafm.com/fluid-128-mp3",
    artwork: "https://api.somafm.com/logos/512/fluid512.jpg?v=1436822727",
    watchUrl: "https://somafm.com/fluid/",
    sourceUrl: "https://somafm.com/fluid/",
    source: "radio",
  },
  {
    id: "somafm-cliqhop",
    title: "cliqhop idm",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Brain Boost"],
    description:
      "Blips'n'beeps backed mostly w/beats. Intelligent Dance Music.",
    audioUrl: "https://ice6.somafm.com/cliqhop-256-mp3",
    artwork: "https://api.somafm.com/logos/512/cliqhop512.png?v=1491429885",
    watchUrl: "https://somafm.com/cliqhop/",
    sourceUrl: "https://somafm.com/cliqhop/",
    source: "radio",
  },
  {
    id: "somafm-defcon",
    title: "DEF CON Radio",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Brain Boost"],
    description: "Music for Hacking. The DEF CON Year-Round Channel.",
    audioUrl: "https://ice6.somafm.com/defcon-256-mp3",
    artwork: "https://api.somafm.com/logos/512/defcon512.png?v=1781243226",
    watchUrl: "https://somafm.com/defcon/",
    sourceUrl: "https://somafm.com/defcon/",
    source: "radio",
  },
  {
    id: "somafm-beatblender",
    title: "Beat Blender",
    creator: "SomaFM",
    category: "Deep Focus",
    moods: ["Deep Focus", "Brain Boost"],
    description: "A late night blend of deep-house and downtempo chill.",
    audioUrl: "https://ice6.somafm.com/beatblender-128-mp3",
    artwork: "https://api.somafm.com/logos/512/beatblender512.png?v=1299186119",
    watchUrl: "https://somafm.com/beatblender/",
    sourceUrl: "https://somafm.com/beatblender/",
    source: "radio",
  },
  {
    id: "youtube-oPVte6aMprI",
    title: "Deep Focus - Music For Studying, Concentration and Work",
    videoId: "oPVte6aMprI",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=oPVte6aMprI",
    sourceUrl: "https://www.youtube.com/watch?v=oPVte6aMprI",
    embedUrl: "https://www.youtube-nocookie.com/embed/oPVte6aMprI?autoplay=0",
    artwork: "https://i.ytimg.com/vi/oPVte6aMprI/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 13938,
  },
  {
    id: "youtube-ITn5Q6W9RQY",
    title: "Deep Focus - Music For Reading, Studying, Work and Concentration",
    videoId: "ITn5Q6W9RQY",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=ITn5Q6W9RQY",
    sourceUrl: "https://www.youtube.com/watch?v=ITn5Q6W9RQY",
    embedUrl: "https://www.youtube-nocookie.com/embed/ITn5Q6W9RQY?autoplay=0",
    artwork: "https://i.ytimg.com/vi/ITn5Q6W9RQY/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 12309,
  },
  {
    id: "youtube-sjkrrmBnpGE",
    title:
      "Ambient Study Music To Concentrate - 4 Hours of Music for Studying, Concentration and Memory",
    videoId: "sjkrrmBnpGE",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=sjkrrmBnpGE",
    sourceUrl: "https://www.youtube.com/watch?v=sjkrrmBnpGE",
    embedUrl: "https://www.youtube-nocookie.com/embed/sjkrrmBnpGE?autoplay=0",
    artwork: "https://i.ytimg.com/vi/sjkrrmBnpGE/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 14272,
  },
  {
    id: "youtube-Ie5GGRkjSXE",
    title:
      "4 Hours of Deep Focus Music for Studying - Concentration Music For Deep Thinking And Focus",
    videoId: "Ie5GGRkjSXE",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=Ie5GGRkjSXE",
    sourceUrl: "https://www.youtube.com/watch?v=Ie5GGRkjSXE",
    embedUrl: "https://www.youtube-nocookie.com/embed/Ie5GGRkjSXE?autoplay=0",
    artwork: "https://i.ytimg.com/vi/Ie5GGRkjSXE/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 14400,
  },
  {
    id: "youtube-JxhBJSJRyqg",
    title:
      "4 Hours of Deep Focus Music For Studying - Music for Deep Concentration",
    videoId: "JxhBJSJRyqg",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=JxhBJSJRyqg",
    sourceUrl: "https://www.youtube.com/watch?v=JxhBJSJRyqg",
    embedUrl: "https://www.youtube-nocookie.com/embed/JxhBJSJRyqg?autoplay=0",
    artwork: "https://i.ytimg.com/vi/JxhBJSJRyqg/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 16608,
  },
  {
    id: "youtube-DsnvRbBJy1w",
    title:
      "4 Hours of Deep Focus Music For Better Concentration And Productivity - Ambient Music for Studying",
    videoId: "DsnvRbBJy1w",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=DsnvRbBJy1w",
    sourceUrl: "https://www.youtube.com/watch?v=DsnvRbBJy1w",
    embedUrl: "https://www.youtube-nocookie.com/embed/DsnvRbBJy1w?autoplay=0",
    artwork: "https://i.ytimg.com/vi/DsnvRbBJy1w/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 13944,
  },
  {
    id: "youtube-ZmojhJU-Iak",
    title:
      "1 Hour of Deep Focus Music To Improve Concentration - Music for Studying, Concentration and Memory",
    videoId: "ZmojhJU-Iak",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=ZmojhJU-Iak",
    sourceUrl: "https://www.youtube.com/watch?v=ZmojhJU-Iak",
    embedUrl: "https://www.youtube-nocookie.com/embed/ZmojhJU-Iak?autoplay=0",
    artwork: "https://i.ytimg.com/vi/ZmojhJU-Iak/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3600,
  },
  {
    id: "youtube-ONraFRVwY6o",
    title:
      "3 Hours of Background Music For Studying - Focus Music for Deep Concentration",
    videoId: "ONraFRVwY6o",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=ONraFRVwY6o",
    sourceUrl: "https://www.youtube.com/watch?v=ONraFRVwY6o",
    embedUrl: "https://www.youtube-nocookie.com/embed/ONraFRVwY6o?autoplay=0",
    artwork: "https://i.ytimg.com/vi/ONraFRVwY6o/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 13280,
  },
  {
    id: "youtube-SjiSEvh6fJs",
    title:
      "Music For Concentration And Focus While Studying - 3 Hours of Ambient Study Music",
    videoId: "SjiSEvh6fJs",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=SjiSEvh6fJs",
    sourceUrl: "https://www.youtube.com/watch?v=SjiSEvh6fJs",
    embedUrl: "https://www.youtube-nocookie.com/embed/SjiSEvh6fJs?autoplay=0",
    artwork: "https://i.ytimg.com/vi/SjiSEvh6fJs/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 13120,
  },
  {
    id: "youtube-jXZAbnn1kTU",
    title:
      "Ambient Study Music To Concentrate - 4 Hours of Music for Studying, Concentration and Memory",
    videoId: "jXZAbnn1kTU",
    category: "Deep Focus",
    moods: ["Deep Focus"],
    creator: "Quiet Quest - Study Music",
    watchUrl: "https://www.youtube.com/watch?v=jXZAbnn1kTU",
    sourceUrl: "https://www.youtube.com/watch?v=jXZAbnn1kTU",
    embedUrl: "https://www.youtube-nocookie.com/embed/jXZAbnn1kTU?autoplay=0",
    artwork: "https://i.ytimg.com/vi/jXZAbnn1kTU/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 13882,
  },
  {
    id: "youtube-lTRiuFIWV54",
    title: "1 A.M Study Session [lofi hip hop]",
    videoId: "lTRiuFIWV54",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=lTRiuFIWV54",
    sourceUrl: "https://www.youtube.com/watch?v=lTRiuFIWV54",
    embedUrl: "https://www.youtube-nocookie.com/embed/lTRiuFIWV54?autoplay=0",
    artwork: "https://i.ytimg.com/vi/lTRiuFIWV54/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3674,
  },
  {
    id: "youtube-rFZHOHl-L8A",
    title: "lofi hip hop radio beats to relax/study to",
    videoId: "rFZHOHl-L8A",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=rFZHOHl-L8A",
    sourceUrl: "https://www.youtube.com/watch?v=rFZHOHl-L8A",
    embedUrl: "https://www.youtube-nocookie.com/embed/rFZHOHl-L8A?autoplay=0",
    artwork: "https://i.ytimg.com/vi/rFZHOHl-L8A/hqdefault.jpg",
    source: "youtube",
  },
  {
    id: "youtube-CFGLoQIhmow",
    title: "lofi hip hop mix beats to relax/study to (Part 1)",
    videoId: "CFGLoQIhmow",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=CFGLoQIhmow",
    sourceUrl: "https://www.youtube.com/watch?v=CFGLoQIhmow",
    embedUrl: "https://www.youtube-nocookie.com/embed/CFGLoQIhmow?autoplay=0",
    artwork: "https://i.ytimg.com/vi/CFGLoQIhmow/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10241,
  },
  {
    id: "youtube-n61ULEU7CO0",
    title: "Best of lofi hip hop 2021 [beats to relax/study to]",
    videoId: "n61ULEU7CO0",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=n61ULEU7CO0",
    sourceUrl: "https://www.youtube.com/watch?v=n61ULEU7CO0",
    embedUrl: "https://www.youtube-nocookie.com/embed/n61ULEU7CO0?autoplay=0",
    artwork: "https://i.ytimg.com/vi/n61ULEU7CO0/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 22258,
  },
  {
    id: "youtube-JCKBaJDRMw4",
    title: "chill music for work lofi beats to stay productive",
    videoId: "JCKBaJDRMw4",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=JCKBaJDRMw4",
    sourceUrl: "https://www.youtube.com/watch?v=JCKBaJDRMw4",
    embedUrl: "https://www.youtube-nocookie.com/embed/JCKBaJDRMw4?autoplay=0",
    artwork: "https://i.ytimg.com/vi/JCKBaJDRMw4/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36000,
  },
  {
    id: "youtube-53gNFOqDFcE",
    title: "study with me [pomodoro] 3 hours of lofi focus music",
    videoId: "53gNFOqDFcE",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=53gNFOqDFcE",
    sourceUrl: "https://www.youtube.com/watch?v=53gNFOqDFcE",
    embedUrl: "https://www.youtube-nocookie.com/embed/53gNFOqDFcE?autoplay=0",
    artwork: "https://i.ytimg.com/vi/53gNFOqDFcE/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10804,
  },
  {
    id: "youtube-1Tl2FtV06qo",
    title: "asian lofi radio beats to relax/study to",
    videoId: "1Tl2FtV06qo",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=1Tl2FtV06qo",
    sourceUrl: "https://www.youtube.com/watch?v=1Tl2FtV06qo",
    embedUrl: "https://www.youtube-nocookie.com/embed/1Tl2FtV06qo?autoplay=0",
    artwork: "https://i.ytimg.com/vi/1Tl2FtV06qo/hqdefault.jpg",
    source: "youtube",
  },
  {
    id: "youtube-l98w9OSKVNA",
    title: "12 A.M Study Session [lofi hip hop]",
    videoId: "l98w9OSKVNA",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=l98w9OSKVNA",
    sourceUrl: "https://www.youtube.com/watch?v=l98w9OSKVNA",
    embedUrl: "https://www.youtube-nocookie.com/embed/l98w9OSKVNA?autoplay=0",
    artwork: "https://i.ytimg.com/vi/l98w9OSKVNA/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3449,
  },
  {
    id: "youtube-wAPCSnAhhC8",
    title: "2 A.M Study Session [lofi hip hop]",
    videoId: "wAPCSnAhhC8",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=wAPCSnAhhC8",
    sourceUrl: "https://www.youtube.com/watch?v=wAPCSnAhhC8",
    embedUrl: "https://www.youtube-nocookie.com/embed/wAPCSnAhhC8?autoplay=0",
    artwork: "https://i.ytimg.com/vi/wAPCSnAhhC8/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3739,
  },
  {
    id: "youtube--FlxM_0S2lA",
    title: "Best of lofi 2018 beats to chill/study to",
    videoId: "-FlxM_0S2lA",
    category: "Lo-fi",
    moods: ["Lo-fi"],
    creator: "Lofi Girl",
    watchUrl: "https://www.youtube.com/watch?v=-FlxM_0S2lA",
    sourceUrl: "https://www.youtube.com/watch?v=-FlxM_0S2lA",
    embedUrl: "https://www.youtube-nocookie.com/embed/-FlxM_0S2lA?autoplay=0",
    artwork: "https://i.ytimg.com/vi/-FlxM_0S2lA/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 6817,
  },
  {
    id: "classical-study-brain-power",
    title:
      "Classical Music for Studying & Brain Power | Mozart, Vivaldi, Tchaikovsky...",
    videoId: "BMuknRb7woc",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=BMuknRb7woc",
    sourceUrl: "https://www.youtube.com/watch?v=BMuknRb7woc",
    embedUrl: "https://www.youtube-nocookie.com/embed/BMuknRb7woc?autoplay=0",
    artwork: "https://i.ytimg.com/vi/BMuknRb7woc/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 5756,
  },
  {
    id: "youtube-mdJU5ogrPMY",
    title: "Classical Music for Studying",
    videoId: "mdJU5ogrPMY",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=mdJU5ogrPMY",
    sourceUrl: "https://www.youtube.com/watch?v=mdJU5ogrPMY",
    embedUrl: "https://www.youtube-nocookie.com/embed/mdJU5ogrPMY?autoplay=0",
    artwork: "https://i.ytimg.com/vi/mdJU5ogrPMY/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 8877,
  },
  {
    id: "youtube-0UN_HbOTTcI",
    title: "Classical Music for Brain Power | Mozart, Beethoven, Vivaldi...",
    videoId: "0UN_HbOTTcI",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=0UN_HbOTTcI",
    sourceUrl: "https://www.youtube.com/watch?v=0UN_HbOTTcI",
    embedUrl: "https://www.youtube-nocookie.com/embed/0UN_HbOTTcI?autoplay=0",
    artwork: "https://i.ytimg.com/vi/0UN_HbOTTcI/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11753,
  },
  {
    id: "youtube-3AkZazth0a0",
    title: "Mozart - Classical Music for Studying, Working & Brain Power",
    videoId: "3AkZazth0a0",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=3AkZazth0a0",
    sourceUrl: "https://www.youtube.com/watch?v=3AkZazth0a0",
    embedUrl: "https://www.youtube-nocookie.com/embed/3AkZazth0a0?autoplay=0",
    artwork: "https://i.ytimg.com/vi/3AkZazth0a0/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11265,
  },
  {
    id: "youtube-9ECZyCmoOb8",
    title: "Classical Music for Studying, Revision and Exam Prep",
    videoId: "9ECZyCmoOb8",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=9ECZyCmoOb8",
    sourceUrl: "https://www.youtube.com/watch?v=9ECZyCmoOb8",
    embedUrl: "https://www.youtube-nocookie.com/embed/9ECZyCmoOb8?autoplay=0",
    artwork: "https://i.ytimg.com/vi/9ECZyCmoOb8/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 8375,
  },
  {
    id: "youtube-mIYzp5rcTvU",
    title:
      "Classical Music for Reading - Mozart, Chopin, Debussy, Tchaikovsky...",
    videoId: "mIYzp5rcTvU",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=mIYzp5rcTvU",
    sourceUrl: "https://www.youtube.com/watch?v=mIYzp5rcTvU",
    embedUrl: "https://www.youtube-nocookie.com/embed/mIYzp5rcTvU?autoplay=0",
    artwork: "https://i.ytimg.com/vi/mIYzp5rcTvU/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 8873,
  },
  {
    id: "youtube-FWrtjSdS0ok",
    title: "Classical Music for When You're on a Deadline",
    videoId: "FWrtjSdS0ok",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=FWrtjSdS0ok",
    sourceUrl: "https://www.youtube.com/watch?v=FWrtjSdS0ok",
    embedUrl: "https://www.youtube-nocookie.com/embed/FWrtjSdS0ok?autoplay=0",
    artwork: "https://i.ytimg.com/vi/FWrtjSdS0ok/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 7561,
  },
  {
    id: "youtube-0AlK7DMSvZs",
    title: "Classical Music for Studying",
    videoId: "0AlK7DMSvZs",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=0AlK7DMSvZs",
    sourceUrl: "https://www.youtube.com/watch?v=0AlK7DMSvZs",
    embedUrl: "https://www.youtube-nocookie.com/embed/0AlK7DMSvZs?autoplay=0",
    artwork: "https://i.ytimg.com/vi/0AlK7DMSvZs/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11584,
  },
  {
    id: "youtube-f_FSWEg9Wgk",
    title: "Classical Music for Late Night Studies",
    videoId: "f_FSWEg9Wgk",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=f_FSWEg9Wgk",
    sourceUrl: "https://www.youtube.com/watch?v=f_FSWEg9Wgk",
    embedUrl: "https://www.youtube-nocookie.com/embed/f_FSWEg9Wgk?autoplay=0",
    artwork: "https://i.ytimg.com/vi/f_FSWEg9Wgk/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11262,
  },
  {
    id: "youtube-51Gm5q6Z07E",
    title: "Mozart | Classical Music for Studying, Working & Brain Power",
    videoId: "51Gm5q6Z07E",
    category: "Classical",
    moods: ["Classical"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=51Gm5q6Z07E",
    sourceUrl: "https://www.youtube.com/watch?v=51Gm5q6Z07E",
    embedUrl: "https://www.youtube-nocookie.com/embed/51Gm5q6Z07E?autoplay=0",
    artwork: "https://i.ytimg.com/vi/51Gm5q6Z07E/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 14599,
  },
  {
    id: "youtube-6GVgncA9oiw",
    title:
      "Beautiful Relaxing Music • Peaceful Piano, Cello & Guitar Music by Soothing Relaxation",
    videoId: "6GVgncA9oiw",
    category: "Ambient",
    moods: ["Ambient", "Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=6GVgncA9oiw",
    sourceUrl: "https://www.youtube.com/watch?v=6GVgncA9oiw",
    embedUrl: "https://www.youtube-nocookie.com/embed/6GVgncA9oiw?autoplay=0",
    artwork: "https://i.ytimg.com/vi/6GVgncA9oiw/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10965,
  },
  {
    id: "youtube-8WVXk0Gz66E",
    title:
      "10 Hours of Relaxing Music - Calm Piano & Guitar, Sleep Music, Study Music",
    videoId: "8WVXk0Gz66E",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=8WVXk0Gz66E",
    sourceUrl: "https://www.youtube.com/watch?v=8WVXk0Gz66E",
    embedUrl: "https://www.youtube-nocookie.com/embed/8WVXk0Gz66E?autoplay=0",
    artwork: "https://i.ytimg.com/vi/8WVXk0Gz66E/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36108,
  },
  {
    id: "youtube-Kad5ZP0unoY",
    title:
      "Beautiful Relaxing Music - Piano, Cello & Guitar Music by Soothing Relaxation",
    videoId: "Kad5ZP0unoY",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=Kad5ZP0unoY",
    sourceUrl: "https://www.youtube.com/watch?v=Kad5ZP0unoY",
    embedUrl: "https://www.youtube-nocookie.com/embed/Kad5ZP0unoY?autoplay=0",
    artwork: "https://i.ytimg.com/vi/Kad5ZP0unoY/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 21630,
  },
  {
    id: "youtube-EbnH3VHzhu8",
    title:
      "10 Hours of Relaxing Music • Sleep Music, Soft Piano Music & Healing Music by Soothing Relaxation",
    videoId: "EbnH3VHzhu8",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=EbnH3VHzhu8",
    sourceUrl: "https://www.youtube.com/watch?v=EbnH3VHzhu8",
    embedUrl: "https://www.youtube-nocookie.com/embed/EbnH3VHzhu8?autoplay=0",
    artwork: "https://i.ytimg.com/vi/EbnH3VHzhu8/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36266,
  },
  {
    id: "youtube-77ZozI0rw7w",
    title:
      "Soothing Relaxation: Relaxing Piano Music & Water Sounds for Sleep, Meditation, Spa & Yoga",
    videoId: "77ZozI0rw7w",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=77ZozI0rw7w",
    sourceUrl: "https://www.youtube.com/watch?v=77ZozI0rw7w",
    embedUrl: "https://www.youtube-nocookie.com/embed/77ZozI0rw7w?autoplay=0",
    artwork: "https://i.ytimg.com/vi/77ZozI0rw7w/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10924,
  },
  {
    id: "youtube-2OEL4P1Rz04",
    title:
      "The Hidden Valley: Ambient Relaxing Music for Stress Relief, Sleep & Meditation",
    videoId: "2OEL4P1Rz04",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=2OEL4P1Rz04",
    sourceUrl: "https://www.youtube.com/watch?v=2OEL4P1Rz04",
    embedUrl: "https://www.youtube-nocookie.com/embed/2OEL4P1Rz04?autoplay=0",
    artwork: "https://i.ytimg.com/vi/2OEL4P1Rz04/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10868,
  },
  {
    id: "youtube-eiV0nvJ9fRM",
    title:
      "7 Hours of Relaxing Sleep Music • Soft Piano Music, Sleeping Music, Sweet Dreams #122",
    videoId: "eiV0nvJ9fRM",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=eiV0nvJ9fRM",
    sourceUrl: "https://www.youtube.com/watch?v=eiV0nvJ9fRM",
    embedUrl: "https://www.youtube-nocookie.com/embed/eiV0nvJ9fRM?autoplay=0",
    artwork: "https://i.ytimg.com/vi/eiV0nvJ9fRM/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 25994,
  },
  {
    id: "youtube-DGQwd1_dpuc",
    title:
      "Relaxing Music with Beautiful Nature - Peaceful Piano & Guitar Music by Soothing Relaxation",
    videoId: "DGQwd1_dpuc",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=DGQwd1_dpuc",
    sourceUrl: "https://www.youtube.com/watch?v=DGQwd1_dpuc",
    embedUrl: "https://www.youtube-nocookie.com/embed/DGQwd1_dpuc?autoplay=0",
    artwork: "https://i.ytimg.com/vi/DGQwd1_dpuc/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10913,
  },
  {
    id: "youtube-3NycM9lYdRI",
    title:
      "Relaxing Piano Music: Romantic Music, Beautiful Relaxing Music, Sleep Music, Stress Relief 122",
    videoId: "3NycM9lYdRI",
    category: "Ambient",
    moods: ["Ambient", "Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=3NycM9lYdRI",
    sourceUrl: "https://www.youtube.com/watch?v=3NycM9lYdRI",
    embedUrl: "https://www.youtube-nocookie.com/embed/3NycM9lYdRI?autoplay=0",
    artwork: "https://i.ytimg.com/vi/3NycM9lYdRI/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 12999,
  },
  {
    id: "youtube-p6wFbdU4Tpc",
    title:
      "Relaxing Harp Music: Stress Relief, Sleep, Meditation, Spa | Instrumental Background Music 53",
    videoId: "p6wFbdU4Tpc",
    category: "Ambient",
    moods: ["Ambient"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=p6wFbdU4Tpc",
    sourceUrl: "https://www.youtube.com/watch?v=p6wFbdU4Tpc",
    embedUrl: "https://www.youtube-nocookie.com/embed/p6wFbdU4Tpc?autoplay=0",
    artwork: "https://i.ytimg.com/vi/p6wFbdU4Tpc/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 21476,
  },
  {
    id: "youtube-eTeD8DAta4c",
    title: "Relaxing Rain Sounds = Drifting to Sleep",
    videoId: "eTeD8DAta4c",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=eTeD8DAta4c",
    sourceUrl: "https://www.youtube.com/watch?v=eTeD8DAta4c",
    embedUrl: "https://www.youtube-nocookie.com/embed/eTeD8DAta4c?autoplay=0",
    artwork: "https://i.ytimg.com/vi/eTeD8DAta4c/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36002,
  },
  {
    id: "youtube-yIQd2Ya0Ziw",
    title:
      "Rainstorm Sounds for Relaxing, Focus or Deep Sleep | Nature White Noise | 8 Hour Video",
    videoId: "yIQd2Ya0Ziw",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Calm",
    watchUrl: "https://www.youtube.com/watch?v=yIQd2Ya0Ziw",
    sourceUrl: "https://www.youtube.com/watch?v=yIQd2Ya0Ziw",
    embedUrl: "https://www.youtube-nocookie.com/embed/yIQd2Ya0Ziw?autoplay=0",
    artwork: "https://i.ytimg.com/vi/yIQd2Ya0Ziw/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 28800,
  },
  {
    id: "youtube-1ejhEVmIFr0",
    title:
      "White Noise Rain Sounds for Sleep, Focus, Studying | Rainstorm 10 Hours",
    videoId: "1ejhEVmIFr0",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=1ejhEVmIFr0",
    sourceUrl: "https://www.youtube.com/watch?v=1ejhEVmIFr0",
    embedUrl: "https://www.youtube-nocookie.com/embed/1ejhEVmIFr0?autoplay=0",
    artwork: "https://i.ytimg.com/vi/1ejhEVmIFr0/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36000,
  },
  {
    id: "youtube-mPZkdNFkNps",
    title:
      "Rain Sound On Window with Thunder SoundsㅣHeavy Rain for Sleep, Study and Relaxation, Meditation",
    videoId: "mPZkdNFkNps",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing Ambience ASMR",
    watchUrl: "https://www.youtube.com/watch?v=mPZkdNFkNps",
    sourceUrl: "https://www.youtube.com/watch?v=mPZkdNFkNps",
    embedUrl: "https://www.youtube-nocookie.com/embed/mPZkdNFkNps?autoplay=0",
    artwork: "https://i.ytimg.com/vi/mPZkdNFkNps/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 28814,
  },
  {
    id: "youtube-buqt6_CjtuI",
    title:
      "Rain Sounds + Stream for Sleep, Focus, Studying | 4K Nature Video White Noise 10 Hours",
    videoId: "buqt6_CjtuI",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=buqt6_CjtuI",
    sourceUrl: "https://www.youtube.com/watch?v=buqt6_CjtuI",
    embedUrl: "https://www.youtube-nocookie.com/embed/buqt6_CjtuI?autoplay=0",
    artwork: "https://i.ytimg.com/vi/buqt6_CjtuI/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36000,
  },
  {
    id: "youtube-4bskZYoO0N0",
    title: "Relaxing Rain Noise + Forest Stream Water Sounds for Sleeping",
    videoId: "4bskZYoO0N0",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=4bskZYoO0N0",
    sourceUrl: "https://www.youtube.com/watch?v=4bskZYoO0N0",
    embedUrl: "https://www.youtube-nocookie.com/embed/4bskZYoO0N0?autoplay=0",
    artwork: "https://i.ytimg.com/vi/4bskZYoO0N0/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36037,
  },
  {
    id: "youtube-o8GrqUSdzi0",
    title:
      "Relaxing Music & Rain Sounds - Beautiful Piano Music, Background Music, Sleep Music • You & Me",
    videoId: "o8GrqUSdzi0",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=o8GrqUSdzi0",
    sourceUrl: "https://www.youtube.com/watch?v=o8GrqUSdzi0",
    embedUrl: "https://www.youtube-nocookie.com/embed/o8GrqUSdzi0?autoplay=0",
    artwork: "https://i.ytimg.com/vi/o8GrqUSdzi0/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36195,
  },
  {
    id: "youtube-MO1wJTMuHXg",
    title: "Sleep Sounds Rain No Thunder Rainstorm White Noise 10 Hours",
    videoId: "MO1wJTMuHXg",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=MO1wJTMuHXg",
    sourceUrl: "https://www.youtube.com/watch?v=MO1wJTMuHXg",
    embedUrl: "https://www.youtube-nocookie.com/embed/MO1wJTMuHXg?autoplay=0",
    artwork: "https://i.ytimg.com/vi/MO1wJTMuHXg/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36036,
  },
  {
    id: "youtube-cLmU29OuI88",
    title:
      "Rainstorm & Ocean Waves | Sleep or Study Better with Rain White Noise | 10 Hours",
    videoId: "cLmU29OuI88",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=cLmU29OuI88",
    sourceUrl: "https://www.youtube.com/watch?v=cLmU29OuI88",
    embedUrl: "https://www.youtube-nocookie.com/embed/cLmU29OuI88?autoplay=0",
    artwork: "https://i.ytimg.com/vi/cLmU29OuI88/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36000,
  },
  {
    id: "youtube-LlKyGAGHc4c",
    title:
      "Rain in Forest White Noise | Sleep, Study, Focus | 10 Hours Rainstorm",
    videoId: "LlKyGAGHc4c",
    category: "Rain Sounds",
    moods: ["Rain Sounds"],
    creator: "Relaxing White Noise",
    watchUrl: "https://www.youtube.com/watch?v=LlKyGAGHc4c",
    sourceUrl: "https://www.youtube.com/watch?v=LlKyGAGHc4c",
    embedUrl: "https://www.youtube-nocookie.com/embed/LlKyGAGHc4c?autoplay=0",
    artwork: "https://i.ytimg.com/vi/LlKyGAGHc4c/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 36000,
  },
  {
    id: "youtube-zoK1swTBKXc",
    title: "Peder B. Helland - Bright Future (Full Album)",
    videoId: "zoK1swTBKXc",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Peder B. Helland",
    watchUrl: "https://www.youtube.com/watch?v=zoK1swTBKXc",
    sourceUrl: "https://www.youtube.com/watch?v=zoK1swTBKXc",
    embedUrl: "https://www.youtube-nocookie.com/embed/zoK1swTBKXc?autoplay=0",
    artwork: "https://i.ytimg.com/vi/zoK1swTBKXc/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 4343,
  },
  {
    id: "youtube-lCOF9LN_Zxs",
    title:
      "Beautiful Piano Music, Vol. 1 | Relaxing Music for Focus, Sleep & Relaxation by Peder B. Helland",
    videoId: "lCOF9LN_Zxs",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation and Peder B. Helland",
    watchUrl: "https://www.youtube.com/watch?v=lCOF9LN_Zxs",
    sourceUrl: "https://www.youtube.com/watch?v=lCOF9LN_Zxs",
    embedUrl: "https://www.youtube-nocookie.com/embed/lCOF9LN_Zxs?autoplay=0",
    artwork: "https://i.ytimg.com/vi/lCOF9LN_Zxs/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3521,
  },
  {
    id: "youtube-hlWiI4xVXKY",
    title:
      "Sunny Mornings: Beautiful Relaxing Music with Piano, Guitar & Bird Sounds by Peder B. Helland",
    videoId: "hlWiI4xVXKY",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=hlWiI4xVXKY",
    sourceUrl: "https://www.youtube.com/watch?v=hlWiI4xVXKY",
    embedUrl: "https://www.youtube-nocookie.com/embed/hlWiI4xVXKY?autoplay=0",
    artwork: "https://i.ytimg.com/vi/hlWiI4xVXKY/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11019,
  },
  {
    id: "youtube-ldgjk2GipP8",
    title: "Beautiful Piano Music, Vol. 5 | Relaxing Music by Peder B. Helland",
    videoId: "ldgjk2GipP8",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=ldgjk2GipP8",
    sourceUrl: "https://www.youtube.com/watch?v=ldgjk2GipP8",
    embedUrl: "https://www.youtube-nocookie.com/embed/ldgjk2GipP8?autoplay=0",
    artwork: "https://i.ytimg.com/vi/ldgjk2GipP8/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 4131,
  },
  {
    id: "youtube-9Q634rbsypE",
    title:
      "Always: Soft, Beautiful & Relaxing Piano Music by Peder B. Helland with Nature Photos",
    videoId: "9Q634rbsypE",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=9Q634rbsypE",
    sourceUrl: "https://www.youtube.com/watch?v=9Q634rbsypE",
    embedUrl: "https://www.youtube-nocookie.com/embed/9Q634rbsypE?autoplay=0",
    artwork: "https://i.ytimg.com/vi/9Q634rbsypE/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11170,
  },
  {
    id: "youtube-QQ-WACJqc4Y",
    title: "Best of Relaxing Piano Music by Peder B. Helland",
    videoId: "QQ-WACJqc4Y",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=QQ-WACJqc4Y",
    sourceUrl: "https://www.youtube.com/watch?v=QQ-WACJqc4Y",
    embedUrl: "https://www.youtube-nocookie.com/embed/QQ-WACJqc4Y?autoplay=0",
    artwork: "https://i.ytimg.com/vi/QQ-WACJqc4Y/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11821,
  },
  {
    id: "youtube-Sg-ucNFd_0s",
    title:
      "Rose Petals: Beautiful, Romantic & Relaxing Piano Music by Peder B. Helland",
    videoId: "Sg-ucNFd_0s",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation",
    watchUrl: "https://www.youtube.com/watch?v=Sg-ucNFd_0s",
    sourceUrl: "https://www.youtube.com/watch?v=Sg-ucNFd_0s",
    embedUrl: "https://www.youtube-nocookie.com/embed/Sg-ucNFd_0s?autoplay=0",
    artwork: "https://i.ytimg.com/vi/Sg-ucNFd_0s/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 11206,
  },
  {
    id: "youtube--b4BjxrIp8o",
    title:
      "Beautiful Piano Music, Vol. 3 | Relaxing Music for Sleep & Relaxation by Peder B. Helland",
    videoId: "-b4BjxrIp8o",
    category: "Instrumental",
    moods: ["Instrumental"],
    creator: "Soothing Relaxation and Peder B. Helland",
    watchUrl: "https://www.youtube.com/watch?v=-b4BjxrIp8o",
    sourceUrl: "https://www.youtube.com/watch?v=-b4BjxrIp8o",
    embedUrl: "https://www.youtube-nocookie.com/embed/-b4BjxrIp8o?autoplay=0",
    artwork: "https://i.ytimg.com/vi/-b4BjxrIp8o/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3235,
  },
  {
    id: "youtube-iCXABsF0-oQ",
    title:
      "Music for Work — Deep Bass Mix for Focus | Chillstep & Future Garage Deep Work Music",
    videoId: "iCXABsF0-oQ",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=iCXABsF0-oQ",
    sourceUrl: "https://www.youtube.com/watch?v=iCXABsF0-oQ",
    embedUrl: "https://www.youtube-nocookie.com/embed/iCXABsF0-oQ?autoplay=0",
    artwork: "https://i.ytimg.com/vi/iCXABsF0-oQ/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10784,
  },
  {
    id: "youtube-f-lNRuzxjKI",
    title: "Work Mode | Ultimate Work Music for Focus & Productivity",
    videoId: "f-lNRuzxjKI",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=f-lNRuzxjKI",
    sourceUrl: "https://www.youtube.com/watch?v=f-lNRuzxjKI",
    embedUrl: "https://www.youtube-nocookie.com/embed/f-lNRuzxjKI?autoplay=0",
    artwork: "https://i.ytimg.com/vi/f-lNRuzxjKI/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 4986,
  },
  {
    id: "youtube-yeb-IGR4G5M",
    title:
      "Deep Work Music | Ambient Focus Beats for Extreme Concentration & Productivity Flow State",
    videoId: "yeb-IGR4G5M",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Deep Citadel",
    watchUrl: "https://www.youtube.com/watch?v=yeb-IGR4G5M",
    sourceUrl: "https://www.youtube.com/watch?v=yeb-IGR4G5M",
    embedUrl: "https://www.youtube-nocookie.com/embed/yeb-IGR4G5M?autoplay=0",
    artwork: "https://i.ytimg.com/vi/yeb-IGR4G5M/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 7492,
  },
  {
    id: "youtube-9ZSwPHI9Lls",
    title: "Deep Work Music — Chill Downtempo Mix for Focus & Productivity",
    videoId: "9ZSwPHI9Lls",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=9ZSwPHI9Lls",
    sourceUrl: "https://www.youtube.com/watch?v=9ZSwPHI9Lls",
    embedUrl: "https://www.youtube-nocookie.com/embed/9ZSwPHI9Lls?autoplay=0",
    artwork: "https://i.ytimg.com/vi/9ZSwPHI9Lls/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10793,
  },
  {
    id: "youtube-Hx2laKXEy-4",
    title: "No AI — Deep Work Music — Absolute Focus State",
    videoId: "Hx2laKXEy-4",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=Hx2laKXEy-4",
    sourceUrl: "https://www.youtube.com/watch?v=Hx2laKXEy-4",
    embedUrl: "https://www.youtube-nocookie.com/embed/Hx2laKXEy-4?autoplay=0",
    artwork: "https://i.ytimg.com/vi/Hx2laKXEy-4/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10800,
  },
  {
    id: "youtube--sZqtdT-GVw",
    title: "Chill Music — Deep Focus & Inspiring Mix",
    videoId: "-sZqtdT-GVw",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=-sZqtdT-GVw",
    sourceUrl: "https://www.youtube.com/watch?v=-sZqtdT-GVw",
    embedUrl: "https://www.youtube-nocookie.com/embed/-sZqtdT-GVw?autoplay=0",
    artwork: "https://i.ytimg.com/vi/-sZqtdT-GVw/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 9186,
  },
  {
    id: "youtube-44Uh1FA_01k",
    title: "Chillout Music for Work & Study — Mix for Calm, Focus",
    videoId: "44Uh1FA_01k",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=44Uh1FA_01k",
    sourceUrl: "https://www.youtube.com/watch?v=44Uh1FA_01k",
    embedUrl: "https://www.youtube-nocookie.com/embed/44Uh1FA_01k?autoplay=0",
    artwork: "https://i.ytimg.com/vi/44Uh1FA_01k/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 3433,
  },
  {
    id: "youtube-SVKQ1EZCMNs",
    title: "Work Music for Deep Focus and Hyper Efficient",
    videoId: "SVKQ1EZCMNs",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=SVKQ1EZCMNs",
    sourceUrl: "https://www.youtube.com/watch?v=SVKQ1EZCMNs",
    embedUrl: "https://www.youtube-nocookie.com/embed/SVKQ1EZCMNs?autoplay=0",
    artwork: "https://i.ytimg.com/vi/SVKQ1EZCMNs/hqdefault.jpg",
    source: "youtube",
  },
  {
    id: "youtube-rcaX1cmIvjA",
    title: "Deep Work Music to Boost Your Focus and Productivity",
    videoId: "rcaX1cmIvjA",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=rcaX1cmIvjA",
    sourceUrl: "https://www.youtube.com/watch?v=rcaX1cmIvjA",
    embedUrl: "https://www.youtube-nocookie.com/embed/rcaX1cmIvjA?autoplay=0",
    artwork: "https://i.ytimg.com/vi/rcaX1cmIvjA/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 10453,
  },
  {
    id: "youtube-xkPiQBMC74A",
    title: "No Distractions. Just Progress. — Productivity Music — No AI Music",
    videoId: "xkPiQBMC74A",
    category: "Brain Boost",
    moods: ["Brain Boost"],
    creator: "Chill Music Lab",
    watchUrl: "https://www.youtube.com/watch?v=xkPiQBMC74A",
    sourceUrl: "https://www.youtube.com/watch?v=xkPiQBMC74A",
    embedUrl: "https://www.youtube-nocookie.com/embed/xkPiQBMC74A?autoplay=0",
    artwork: "https://i.ytimg.com/vi/xkPiQBMC74A/hqdefault.jpg",
    source: "youtube",
    durationSeconds: 4883,
  },
  {
    id: "vivaldi-four-seasons",
    title: "Vivaldi: The Four Seasons (Orquesta Reino de Aragón)",
    videoId: "4rgSzQwe5DQ",
    category: "Classical",
    moods: ["Classical", "Instrumental"],
    creator: "HALIDONMUSIC",
    watchUrl: "https://www.youtube.com/watch?v=4rgSzQwe5DQ",
    sourceUrl: "https://www.youtube.com/watch?v=4rgSzQwe5DQ",
    embedUrl: "https://www.youtube-nocookie.com/embed/4rgSzQwe5DQ?autoplay=0",
    artwork: "https://i.ytimg.com/vi/4rgSzQwe5DQ/hqdefault.jpg",
    source: "youtube",
  },
  {
    id: "mozart-piano-concerto-21-andante",
    title:
      "Dayou Kim- W.A. Mozart piano concerto No.21 in C Major K.467 II. Andante",
    videoId: "w8BRnjahses",
    category: "Classical",
    moods: ["Classical", "Instrumental"],
    creator: "Dayou Kim",
    watchUrl: "https://www.youtube.com/watch?v=w8BRnjahses",
    sourceUrl: "https://www.youtube.com/watch?v=w8BRnjahses",
    embedUrl: "https://www.youtube-nocookie.com/embed/w8BRnjahses?autoplay=0",
    artwork: "https://i.ytimg.com/vi/w8BRnjahses/hqdefault.jpg",
    source: "youtube",
  },
];
export function getCuratedTracks(): readonly CuratedTrack[] {
  return CURATED_TRACKS;
}
export function findCuratedTrackById(id: string): CuratedTrack | undefined {
  return CURATED_TRACKS.find((track) => track.id === id);
}
export function tracksForMood(
  mood: StudyMood | "All",
): readonly CuratedTrack[] {
  return mood === "All"
    ? CURATED_TRACKS
    : CURATED_TRACKS.filter((track) => track.moods.includes(mood));
}
export function trackDuration(track: CuratedTrack): string {
  if (!track.durationSeconds)
    return track.source === "radio" ? "Live radio" : "Stream";
  const hours = Math.floor(track.durationSeconds / 3600);
  const minutes = Math.floor((track.durationSeconds % 3600) / 60);
  return hours ? `${hours}h ${minutes}m` : `${minutes}m`;
}
